[package]
name = "dekoos"
version = "0.0.1"
authors = ["dekokun"]

[lib]
path = "src/bootpack.rs"
crate-type = ["staticlib"]

[profile.dev]
panic = "abort"
opt-level = 0
debug = true

[profile.release]
panic = "abort"
opt-level = 2

[dependencies]
rlibc = "1.0.0"
